name: PR Develop to Main (no duplicates)

on:
  schedule:
    - cron: '0 */6 * * *' # a cada 6 horas
  workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check for changes
        id: changes
        run: |
          git fetch origin main
          git diff --quiet origin/main..origin/develop || echo "changes=true" >> $GITHUB_ENV

      - name: Check for existing PR
        id: check-pr
        uses: octokit/request-action
        if: env.changes == 'true'
        with:
          route: GET /repos/${{ github.repository }}/pulls
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
          head: develop
          base: main

      - name: Create Pull Request
        if: env.changes == 'true' && steps.check-pr.outputs.data == '[]'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: develop
          title: "Sync develop → main"
          body: "Atualização automática da branch develop para main"
